export const data = [
  {
    id: 1,
    title: "Apartment El Houda",
    image: "im1.jpg",
    features: ["King Beds", "Air-conditioner", "Free Wifi"],
    description:
      "El Houda neque asperiores quisquam illum distinctio doloremque quae dolorum, possimus totam!",
    star: 3,
    price: 89,
    bestSeller: true,
    royal: true,
    costal: false,
  },
  {
    id: 2,
    title: "Apartment Tamanarte",
    image: "im2.jpg",
    features: ["Twin Beds", "Air-conditioner", "Tv"],
    description:
      "Tamanarte neque asperiores quisquam illum distinctio doloremque quae dolorum, possimus totam!",
    star: 3,
    price: 67,
    bestSeller: false,
    royal: false,
    costal: false,
  },
  {
    id: 3,
    title: "Apartment Safi",
    image: "im3.jpg",
    features: ["Roal Bed", "Air-conditioner", "swimming pool"],
    description:
      "Safi neque asperiores quisquam illum distinctio doloremque quae dolorum, possimus totam!",
    star: 3,
    price: 82,
    bestSeller: true,
    royal: true,
    costal: false,
  },
  {
    id: 4,
    title: "Apartment Marrakech",
    image: "im4.jpg",
    features: ["King Beds", "Free Wifi", "Balcony"],
    description:
      "Marrakech neque asperiores quisquam illum distinctio doloremque quae dolorum, possimus totam!",
    star: 3,
    price: 98,
    bestSeller: true,
    royal: false,
    costal: false,
  },
  {
    id: 5,
    title: "Apartment Standard",
    image: "im5.jpg",
    features: ["Twin Beds", "Air-conditioner", "Free Wifi"],
    description:
      "Standard neque asperiores quisquam illum distinctio doloremque quae dolorum, possimus totam!",
    star: 0,
    price: 75,
    bestSeller: false,
    royal: false,
    costal: false,
  },
  {
    id: 6,
    title: "Apartment Agadir",
    image: "im6.jpg",
    features: ["Queen Bed", "Parking", "Free Wifi"],
    description:
      "Agadir neque asperiores quisquam illum distinctio doloremque quae dolorum, possimus totam!",
    star: 0,
    price: 98,
    bestSeller: false,
    royal: true,
    costal: true,
  },
];
